// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WackyBusinessCards.Data;

#nullable disable

namespace WackyBusinessCards.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250519200001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WackyBusinessCards.Models.BusinessCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("BorderRadius")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BorderStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BorderWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialEffect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BusinessCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Chocolate Factory Way, Loompaland",
                            BackgroundColor = "#9b59b6",
                            BorderColor = "#f1c40f",
                            BorderRadius = 15,
                            BorderStyle = "dashed",
                            BorderWidth = 5,
                            Company = "Wonka Industries",
                            Email = "willy@wonkachocolate.com",
                            FontFamily = "'Comic Sans MS', cursive",
                            ImageUrl = "/images/chocolate.png",
                            Name = "Willy Wonka",
                            Phone = "555-CHOCOLATE",
                            SpecialEffect = "rotate",
                            TextColor = "#ffffff",
                            Title = "Chocolate Extraordinaire",
                            Website = "www.wonkachocolate.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Somewhere in the Caribbean",
                            BackgroundColor = "#34495e",
                            BorderColor = "#c0392b",
                            BorderRadius = 0,
                            BorderStyle = "double",
                            BorderWidth = 7,
                            Company = "Black Pearl Enterprises",
                            Email = "captain@blackpearl.sea",
                            FontFamily = "'Pirata One', cursive",
                            ImageUrl = "/images/pirate.png",
                            Name = "Captain Jack Sparrow",
                            Phone = "ARRRR-MATEY",
                            SpecialEffect = "shadow",
                            TextColor = "#f1c40f",
                            Title = "Pirate Captain",
                            Website = "www.pirateslife.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ottery St. Catchpole",
                            BackgroundColor = "#3498db",
                            BorderColor = "#e74c3c",
                            BorderRadius = 30,
                            BorderStyle = "dotted",
                            BorderWidth = 3,
                            Company = "The Quibbler",
                            Email = "luna@quibbler.wiz",
                            FontFamily = "'Indie Flower', cursive",
                            ImageUrl = "/images/magic.png",
                            Name = "Luna Lovegood",
                            Phone = "PATRONUS-123",
                            SpecialEffect = "sparkle",
                            TextColor = "#ffffff",
                            Title = "Magizoologist",
                            Website = "www.thequibbler.wiz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
